spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/greengram5
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: aw4gw4fw4gw4g
            clientSecret: aw4gaw4g234g24g
            scope:
              - email
              - profile
          facebook:
            clientId: aefsef24f24f2f4
            clientSecret: aw4fw4f4g4
            scope:
              - email
              - public_profile
          naver:
            client-id: 2LoQMA0bXPtroEdUGGye
            client-secret: IyKA580HjK
            #clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: 284230c61081b7545eb2f849beef4bc1
            client-secret: xLIgwp7EsEEsuPwvz0rpeStcNnR80vdt
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            #redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
#              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id



file:
  dir: D:/download/greengram4/

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

fcm:
  certification: serviceAccountKey.json


#logging:
#  level:
#    com.green.greengram4.user: debug
#    com.green.greengram4.feed: debug


#커스텀 암호화 키
app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-schema-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8080/oauth/redirect
      - http://192.168.0.144:5225/oauth/redirect
      - http://localhost:3000/oauth/redirect

logging:
  level:
    -com.green.greengram4: debug


openapi:
  apartment:
    base-url: http://openapi.molit.go.kr
    data-url: OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: Y2UOCkD8Ilv2gViPGV33ddNTTQfRi92i8mRzUeQX%2BNgSiNTO3gp9hJZX4J6u8uXucMM6RdRBoGxMn6XHfsEzNA%3D%3D

---
spring:
  config:
    activate:
      on-profile: prod2

server:
  port: 8082